# Jupyter Notebooks  2/2  
##  Jornadas Engenharia Biomédica 2023 
### Paulo Ferreira pdf@isep.ipp.pt



### Miscelaneous Stuff  

* Magic commands 
* Useful Libraries  	

In [ ]:
%magic

In [1]:
%ls -l 

16.13s - pydevd: Sending message related to process being replaced timed-out after 5 seconds


total 240
-rw-rw-rw-  1 codespace root  3076 May 31 08:01 Course_Python00.ipynb
-rw-rw-rw-  1 codespace root 17738 May 31 08:01 Course_Python01.ipynb
-rw-rw-rw-  1 codespace root 76309 May 31 08:01 Course_Python02.ipynb
-rw-rw-rw-  1 codespace root 45903 May 31 08:01 Course_Python03.ipynb
-rw-rw-rw-  1 codespace root 11613 May 31 08:01 DemosJupyter01.ipynb
-rw-rw-rw-  1 codespace root 20891 May 31 08:13 DemosJupyter02.ipynb
-rw-rw-rw-  1 codespace root  3691 May 31 08:01 Exercises01.ipynb
-rw-rw-rw-  1 codespace root  8203 May 31 08:01 Exercises02.ipynb
-rw-rw-rw-  1 codespace root    99 May 31 08:01 README.md
-rw-rw-rw-  1 codespace root  8816 May 31 08:01 fich01.xlsx
-rw-rw-rw-  1 codespace root    30 May 31 08:01 file001.csv
-rw-rw-rw-  1 codespace root    22 May 31 08:01 file002.csv
drwxrwxrwx+ 2 codespace root  4096 May 31 08:01 images/
-rw-rw-rw-  1 codespace root   444 May 31 08:01 mymodule.py
-rw-rw-rw-  1 codespace root    87 May 31 08:01 text001.txt
-rw-rw-rw-  1 codespace ro

### nbgrader 

A Jupyter extension to grade student's work :

* Code & Manual grading 

* [https://github.com/jupyter/nbgrader](https://github.com/jupyter/nbgrader)
* [https://nbgrader.readthedocs.io/en/stable/](https://nbgrader.readthedocs.io/en/stable/)
* [YouTube Video 24 min](https://www.youtube.com/watch?v=5WUm0QuJdFw)



### Matplotlib 

* A 2D Plotting library for publication quality figures
* [https://matplotlib.org](https://matplotlib.org)
* Examples taken from the official site

In [ ]:
# start with the magic command!  
%matplotlib inline 
import matplotlib
import numpy as np
import matplotlib.pyplot as plt
 
x = np.linspace(0, 3*np.pi, 500)
plt.plot(x, np.sin(x**2))
plt.title('A simple chirp')
plt.show()

In [ ]:
# start with the magic command!  
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

# Data for plotting
x1 = np.linspace(0.0, 5.0)
x2 = np.linspace(0.0, 2.0)
y1 = np.cos(2 * np.pi * x1) * np.exp(-x1)
y2 = np.cos(2 * np.pi * x2)

# Create two subplots sharing y axis
fig, (ax1, ax2) = plt.subplots(2, sharey=True)

ax1.plot(x1, y1, 'ko-')
ax1.set(title='A tale of 2 subplots', ylabel='Damped oscillation')

ax2.plot(x2, y2, 'r.-')
ax2.set(xlabel='time (s)', ylabel='Undamped')

plt.show()

In [ ]:
%matplotlib inline 
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import MaxNLocator
from collections import namedtuple


n_groups = 5

means_men = (20, 35, 30, 35, 27)
std_men = (2, 3, 4, 1, 2)

means_women = (25, 32, 34, 20, 25)
std_women = (3, 5, 2, 3, 3)

fig, ax = plt.subplots()

index = np.arange(n_groups)
bar_width = 0.35

opacity = 0.4
error_config = {'ecolor': '0.3'}

rects1 = ax.bar(index, means_men, bar_width,
                alpha=opacity, color='b',
                yerr=std_men, error_kw=error_config,
                label='Men')

rects2 = ax.bar(index + bar_width, means_women, bar_width,
                alpha=opacity, color='r',
                yerr=std_women, error_kw=error_config,
                label='Women')

ax.set_xlabel('Group')
ax.set_ylabel('Scores')
ax.set_title('Scores by group and gender')
ax.set_xticks(index + bar_width / 2)
ax.set_xticklabels(('A', 'B', 'C', 'D', 'E'))
ax.legend()

fig.tight_layout()
plt.show()


### Bokeh 

* A library for interactive Web Graphics 
* Bokeh *generates* all the required Javascript code 
* [https://bokeh.pydata.org/en/latest/](https://bokeh.pydata.org/en/latest/)
* Examples taken from the official site

In [1]:
import numpy as np # we will use this later, so import it now

from bokeh.io import output_notebook, show
from bokeh.plotting import figure
output_notebook()

Loading BokehJS ...

In [3]:
# create a new plot with default tools, using figure
p = figure(width=400, height=400)

# add a circle renderer with x and y coordinates, size, color, and alpha
p.circle([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], size=15, line_color="navy", fill_color="orange", fill_alpha=0.5)

show(p) # show the results

In [4]:
# create a new plot (with a title) using figure
p = figure(width=400, height=400, title="My Line Plot")

# add a line renderer
p.line([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], line_width=2)

show(p) # show the results

In [12]:

# Here is a list of categorical values (or factors)
fruits = ['Apples', 'Pears', 'Nectarines', 'Plums', 'Grapes', 'Strawberries']

# Set the x_range to the list of categories above
p = figure(x_range=fruits, height=250, title="Fruit Counts")

# Categorical values can also be used as coordinates
p.vbar(x=fruits, top=[5, 3, 4, 2, 4, 6], width=0.9)

# Set some properties to make the plot look better
p.xgrid.grid_line_color = None
p.y_range.start = 0

show(p)

In [7]:

from bokeh.models import ColumnDataSource
from bokeh.palettes import Spectral6

fruits = ['Apples', 'Pears', 'Nectarines', 'Plums', 'Grapes', 'Strawberries']
counts = [5, 3, 4, 2, 4, 6]

source = ColumnDataSource(data=dict(fruits=fruits, counts=counts, color=Spectral6))

p = figure(x_range=fruits, height=250, y_range=(0, 9), title="Fruit Counts")
p.vbar(x='fruits', top='counts', width=0.9, color='color', legend_label="fruits", source=source)

p.xgrid.grid_line_color = None
p.legend.orientation = "horizontal"
p.legend.location = "top_center"

show(p)

In [10]:
from bokeh.palettes import GnBu3, OrRd3

years = ['2015', '2016', '2017']

exports = {'fruits' : fruits,
           '2015'   : [2, 1, 4, 3, 2, 4],
           '2016'   : [5, 3, 4, 2, 4, 6],
           '2017'   : [3, 2, 4, 4, 5, 3]}
imports = {'fruits' : fruits,
           '2015'   : [-1, 0, -1, -3, -2, -1],
           '2016'   : [-2, -1, -3, -1, -2, -2],
           '2017'   : [-1, -2, -1, 0, -2, -2]}

p = figure(y_range=fruits, height=250, x_range=(-16, 16), title="Fruit import/export, by year")

p.hbar_stack(years, y='fruits', height=0.9, color=GnBu3, source=ColumnDataSource(exports),
             legend_label=["%s exports" % x for x in years])

p.hbar_stack(years, y='fruits', height=0.9, color=OrRd3, source=ColumnDataSource(imports),
             legend_label=["%s imports" % x for x in years])

p.y_range.range_padding = 0.1
p.ygrid.grid_line_color = None
p.legend.location = "center_left"

show(p)

In [ ]:
from bokeh.models import HoverTool

source = ColumnDataSource(
        data=dict(
            x=[1, 2, 3, 4, 5],
            y=[2, 5, 8, 2, 7],
            desc=['A', 'b', 'C', 'd', 'E'],
        )
    )

hover = HoverTool(
        tooltips=[
            ("index", "$index"),
            ("(x,y)", "($x, $y)"),
            ("desc", "@desc"),
        ]
    )

p = figure(plot_width=300, plot_height=300, tools=[hover], title="Mouse over the dots")

p.circle('x', 'y', size=20, source=source)

show(p)

In [14]:
# interactor support 

from ipywidgets import interact
import numpy as np

from bokeh.io import push_notebook, show, output_notebook
from bokeh.plotting import figure
output_notebook()

x = np.linspace(0, 2*np.pi, 2000)
y = np.sin(x)

p = figure(title="simple line example", height=300, width=600, y_range=(-5,5),
           background_fill_color='#efefef')
r = p.line(x, y, color="#8888cc", line_width=1.5, alpha=0.8)

def update(f, w=1, A=1, phi=0):
    if   f == "sin": func = np.sin
    elif f == "cos": func = np.cos
    r.data_source.data['y'] = A * func(w * x + phi)
    push_notebook()

Loading BokehJS ...

In [15]:
show(p, notebook_handle=True)
interact(update, f=["sin", "cos"], w=(0,50), A=(1,10), phi=(0, 20, 0.1))

interactive(children=(Dropdown(description='f', options=('sin', 'cos'), value='sin'), IntSlider(value=1, descr…

<function __main__.update(f, w=1, A=1, phi=0)>

###  Requests

* A library for http 1.1 

[http://docs.python-requests.org](http://docs.python-requests.org)

[https://2.python-requests.org/en/master/user/quickstart/](https://2.python-requests.org/en/master/user/quickstart/)
    

In [ ]:
from PIL import Image 
import matplotlib.pyplot as plt
import requests
# headers.common['x-api-key'] = "DEMO-API-KEY"
r = requests.get('https://api.thecatapi.com/v1/images/search',headers={'x-api-key':"DEMO-API-KEY"})
print(r.status_code)
print(r.headers['content-type']) 
print(r.json())                  
url=r.json()[0]['url']
print(url)
#Image(url)

response = requests.get(url, stream=True)
img = Image.open(response.raw)

plt.imshow(img)
plt.show()


In [ ]:
from IPython.display import Image    
import requests
r = requests.get('https://dog.ceo/api/breeds/image/random')
print(r.status_code)
print(r.headers['content-type']) 
print(r.json())                  
url=r.json()['message']
print(url)
Image(url,width=300, height=300)



### Numpy - Numerical Library 

Lots of mathematical functions 


[https://www.numpy.org/](https://www.numpy.org/)

See also SciPy Lecture Notes:

[https://scipy-lectures.org](https://scipy-lectures.org)

In [16]:
# Numpy example -- ex10_01.py

import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11, 12])
# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


### Pandas 

A statistical data analysis library 


[https://pandas.pydata.org/](https://pandas.pydata.org/)

In [ ]:
# install the pandas_datareader package 
# needed for the following example

%pip install pandas_datareader

In [1]:
# read the MSFT (Microsoft) stock quotes from Yahoo since 2023/01/01
# see the beginning and the end of the data, and a statistical description

import pandas as pd
from pandas_datareader import data as pdr

import yfinance as yf 
yf.pdr_override()

import datetime

msft = pdr.get_data_yahoo('MSFT',start="2023-01-01",end="2023-06-01")

print(msft.head())
print(msft.tail())
print(msft.describe())

ModuleNotFoundError: No module named 'yfinance'

In [ ]:
# read an Excel file 

import pandas as pd
xl=pd.ExcelFile("fich01.xlsx")
print(xl.sheet_names)
df = xl.parse(xl.sheet_names[0])  # get the first sheet
print(df.head())
print(df.corr())   # correlation
print(df.mean())
print(df.describe())


### Issues with Jupyter Notebooks 

* Executing cells in a random order 
* Easy to experiment (bad habits)   
* .ipynb file is a JSON file 
* Integration with version control 
* A good text editor (or IDE) is more helpful/powerful 
* Copy/Paste from/to Notebooks 

### Things that are interesting 

* Remote graphical access to more powerful computers 
* Ease of use 
* Availability 
* Automatic generation of containers on-demand 

**[datalore.io](datalore.io)** 

* Autocompletion online 
* Integration with version control (some do it with hooks) 
* Collaborative editing 
* More stuff I don't know about 


### The End
